### ISSUE TITLE
How to customize treeString & valueTreeString?

### ISSUE THREAD

**Issue by NicolasRouquette** [nikita-volkov/sext#3]
I experimented with the following approach:

```
trait TreeString {
    def treeString: String
  }
```

and modifying treeString as follows:

```
    /**
     * @return A readable string representation of this value
     */
    def treeString
    : String
    = a match {
      case x : Traversable[_] =>
        x.stringPrefix + ":\n" +
          x.view
            .map{ _.treeString }
            .map{ indent }
            .mkString("\n")
      case x : TreeString =>
        x.treeString
      case x : Product if x.productArity == 0 =>
        x.productPrefix
      case x : Product =>
        x.productPrefix + ":\n" +
          x.productIterator
            .map{ _.treeString }
            .map{ indent }
            .mkString("\n")
      case null =>
        "null"
      case _ =>
        a.toString
    }
```

It works as long as one can extend the TreeString trait where one needs to customize the treeString method. Is there an alternative that doesn't require specializing a known trait?

**Comment by nikita-volkov** [comment]
I'm not sure what you're asking here. The package provides `treeString` as an implicit method for any object.

**Comment by NicolasRouquette** [comment]
`treeString` and `toString` have similar purposes: provide a string representation of an object of a given type. Can the similarity be extended to overriding their behavior?

The trait that I showed allows me to do this; however, it requires modifying the type to extend the trait and to override `treeString`. Is there a way to override the `treeString` behavior for a given type without modifying that type?

**Comment by nikita-volkov** [comment]
> Is there a way to override the treeString behavior for a given type without modifying that type?

You can't override a method of a type, which you don't inherit, neither can you do that without modifying the type. You can however extend the existing types with new APIs using implicit extension-methods (as is done in this library) or, better, the Type-class pattern. But all that doesn't have much to do with "sext" particularly, as those are general concepts of the Scala language.

**Comment by NicolasRouquette** [comment]
With the implicit extension method approach used in this library, is it possible to override `treeString`?

Consider the example you commented on: http://stackoverflow.com/a/15718964/1009693

Is it possible to override `treeString` for VarDecl without modifying VarDecl?

**Comment by nikita-volkov** [comment]
Since the extension method approach does not involve inheritance, overriding is simply inapplicable to it. You can provide your own extension methods or declare new methods with other names or use other Scala's approaches, but, again, you need to address the general documentation on those approaches.

**Comment by NicolasRouquette** [comment]
Thanks for the clarifications.
